# Generated by Django 4.2.2 on 2023-07-28 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogName', models.CharField(max_length=20)),
                ('dogAge', models.IntegerField()),
                ('gaurdianContact', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('healthDescription', models.TextField()),
            ],
        ),
    ]
