# Generated by Django 4.2.2 on 2023-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_rename_msg_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dogPicture',
            field=models.ImageField(null=True, upload_to='dogImages/'),
        ),
    ]
